# Generated by Django 3.2.16 on 2023-01-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMaster',
            fields=[
                ('brand_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('brand_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('category_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('category_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('product_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500, null=True)),
                ('product_description', models.TextField(null=True)),
                ('product_stock', models.IntegerField(null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_rating', models.FloatField(null=True)),
                ('product_like', models.IntegerField(null=True)),
                ('product_views', models.TextField(null=True)),
                ('product_sell', models.BigIntegerField(null=True)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brandmaster')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categorymaster')),
            ],
        ),
    ]
