# Generated by Django 3.2.16 on 2023-01-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaster',
            old_name='product_stock',
            new_name='product_qty',
        ),
        migrations.RenameField(
            model_name='productmaster',
            old_name='product_sell',
            new_name='product_sold',
        ),
    ]
