# Generated by Django 3.2.16 on 2023-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230127_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmaster',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='brand images'),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category images'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product images'),
        ),
    ]
