# Generated by Django 3.2.16 on 2023-01-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230127_2136'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmaster',
            table='product_master',
        ),
    ]
